### ISSUE TITLE
Cool site

### ISSUE THREAD

**Issue by DwarfFighterCleric** [DusteDdk/unfinishedsidescrollerfrom2013#1]
Just found your site searching for a fix to run Soldier of Fortune, I hear good stuff about that game and would like to try it, my 64-bit linux don't like it apparently. I already had the "OpenGL Extensions" fix a while ago for running Sin (another quake2 engine game) so that's not the problem. My problem is that the game (on Wine) can't find my opengl 32-bit libraries, but I have them installed, I even have all the symlinks there on system directories. So I'm out of ideas of how to fix it. I will try the Loki native installer I just found.
When you installed those 32-bit libraries you mention, did you have to create additional symlinks or anything fancy? Did you have to run the game after using "EXPORT" variables or the such? I'm at my wits end.
And you're right, Mycrotchsoft sucks!

**Comment by DwarfFighterCleric** [comment]
And hey... forgot something... would you make videos showing all these "pseudo games" of yours there? I'm curious xDDDD  And would be cool if you highlighted some programming mistakes you did back in the day and how would you do the same section of the code nowadays

**Comment by DusteDdk** [comment]
It could be fun to do some videos of those, I'll definitly have that in mind! 

For WINE, I don't recall having to do anything special to get it working, I've had lots of luck with other 32 bit OpenGL stuff (even Carmageddon 2 in Glide mode with the Glide->OpenGL wrapper works fine, and that's as 32 bit as you get).

Maybe your wine is a 64 bit version? I'm using this silly program "playonlinux" to manage multiple WINE installations (and "C:" drives), it will let you do stuff like create a 32 bit wine installation in a specific version. Maybe give that a spin?

The things I had to export was, afaik, the pulseaudio wrapper and the resolution hack. Hmm, but those are described on the resolution hack page.
The resolution hack is for the 32 bit Linux version.
Last time I tried, I got into trouble with the audio messing up the game and making it, I remember doing a lot of random debugging and was able to get it running after overwriting the function that was supposed to play the samples, but then, well, there's no audio.

Good luck! :)

**Comment by DwarfFighterCleric** [comment]
Well, yeah I'm not new to Wine so I know the tricks and whatnot, I have multiple other old games that work fine, so it's a mystery to me why that particular game cannot "recognize" the OpenGL drivers, it has something to do with the way the quake 2 engine was coded, because I heard of people going through similar problems trying to run vanilla (original EXE) quake 2, Doom 3, even Quake 3 the same error messages... But anyway, I will try those methods in the next weeks when I find some gap in the schedule. There's always some time for nerdy stuff right XDDD Bye and thanks
